### PR TITLE
update 'jade' to 'pug'

### LINKED ISSUE #11: Jade has been renamed to Pug
Hi! So Jade has been renamed to Pug and while it is possible to use this view generator and manually change the view engine a la [this resolved issue](https://github.com/balderdashy/sails/issues/3703), it would be nice to be able to start new projects cleanly using: 
``` bash
sails new my-project --template=pug
```
I'm not sure the best way to handle this - I'll create a PR with changes the best way I can think of, please let me know if there's anything else I can do! Thanks!

**Update:** here's the PR: https://github.com/balderdashy/sails-generate-views-jade/pull/12

### PR DESCRIPTION
**Pull request by heatherbooker**
to resolve [this issue for about jade being renamed to pug](https://github.com/balderdashy/sails-generate-views-jade/issues/11)

### CODE REVIEW

**Comment by sgress454** [comment]
Hi Heather, thanks for your work on this!  I tried this with the latest Sails 1.0 pre-release and the latest Pug, and found a couple of issues.  Once these are resolved, we can merge:

* The templates aren't using the latest webfonts.  See the latest [homepage](https://github.com/balderdashy/sails-generate/blob/master/lib/core-generators/new/templates/views/homepage.ejs), [404 page](https://github.com/balderdashy/sails-generate/blob/master/lib/core-generators/new/templates/views/404.ejs) and [500 page](https://github.com/balderdashy/sails-generate/blob/master/lib/core-generators/new/templates/views/500.ejs) source for the new link tag.
* There's some spacing issues in the homepage copy (e.g. under "Generate a REST API", it the last sentence ends with "amodeland acontroller")
* Pug spit out errors and refused to show the 404 and 500 pages b/c `Only named blocks and mixins can appear at the top level of an extending template`.  Moving the comment block beneath the `block body` statement seems to fix this.
* In `layout.pug`, please change the URL of the `sails.io.js` file to `script(src="dependencies/sails.io.js")`

To test this all out:

1. Install the latest Sails 1.0 pre-release w/ `npm install sails@edge -g`
2. In your home directory (e.g. `/Users/heather`), create or open a `.sailsrc` file and make sure it includes:
```
"generators": {
  "modules": {
    "views": "/path/to/sails-generate-views-jade"
  }
}
```
3. Create a new Sails 1.0 app w/ `sails new test-jade-views && cd test-jade-views`
4. `npm install pug && npm install consolidate`
5. In the new app's `config/views.js` file, set:
```
  'extension': 'pug',
  'getRenderFn': function() {
    // Import `consolidate`.
    var cons = require('consolidate');
    // Return the rendering function for Swig.
    return cons.pug;
  }
```
6. `sails lift` and check the various views!

If you don't want to install Sails 1.0 globally, you can just check it out from Github into a folder, and create a new Sails 1.0 app with `/path/to/sails-1.0/bin/sails.js new test-jade-views`.

**Comment by heatherbooker** [comment]
Great, thanks so much for that super clear response! I made the changes you requested and checked out the views. Out of curiousity, how should I have tested all the views? I thought that putting them in  `config/routes.js` as 
```
...
  '500': {
    view: '500'
  },
  ...
}
```
should have made them accessible from localhost:1337/500 etc, but that wasn't the case, so I would love to know how I could have done that. Thanks so much!

**Comment by heatherbooker** [comment]
Hey @sgress454 ! Just wanted to let you know I made the changes you asked for; I would love an update on this when you have a moment. Thanks!

**Comment by sgress454** [comment]
Hi @heatherbooker, sorry for the delay -- looking now

**Comment by sgress454** [comment]
Looks good!  To answer your question from earlier, an easy way to test any response is to use the ["response" route target syntax](http://sailsjs.com/documentation/concepts/routes/custom-routes#?response-target-syntax), for example:

```
'/500': { response: 'serverError' }
```

or else just pop in a quick-n-dirty handler function:

```
'/500': function (req, res) { return res.serverError(new Error('oh no!')); }
```

**Comment by heatherbooker** [comment]
Awesome, thank you so much! :)

**Pull request merged**
